version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "ahmadk953"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
