name: Feature request
description: Suggest an idea to improve the Poixpixel Discord bot.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please search existing issues first.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
