name: Documentation
description: Report an issue or suggest an improvement in the docs.
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the documentation!
  - type: input
    id: page
    attributes:
      label: Page or section
      description: Which page or section is affected?
      placeholder: ex. docs/getting-started/basic-configuration.md
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current content
      description: What's confusing, missing, or incorrect?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
      description: What would you like to improve or add?
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or examples
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
