name: ESLint

on:
  push:
  pull_request:
  schedule:
    - cron: "25 21 * * 1"

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn dlx eslint ./src
          --config eslint.config.mjs
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
